### ISSUE TITLE
Cannot compile package using roptim on Windows

### ISSUE THREAD

**Issue by SachaEpskamp** [ypan1988/roptim#2]
Dear Yi Pan,

Thank you for the roptim package! It works very well and seems to be exactly what I was looking for. I am working on a developmental version of my R package [psychonetrics](https://github.com/SachaEpskamp/psychonetrics) which uses roptim in [this c++ code](https://github.com/SachaEpskamp/psychonetrics/blob/master/src/04_generalfit_psychonetrics_BFGS.cpp). The package works well on Linux, but when trying to compile the package on Windows I get the following errors:

![image](https://user-images.githubusercontent.com/1207242/77642707-61677300-6f5e-11ea-83f8-04688ecd238a.png)

I am entirely at a loss what this error could be, which seems not to be related to the source code of my package at all. I tried commenting out lines 82 - 85 of [the code that uses roptim](https://github.com/SachaEpskamp/psychonetrics/blob/master/src/04_generalfit_psychonetrics_BFGS.cpp), but this did not solve the problem.

Thank you very much for your time!

**Comment by ypan1988** [comment]
Dear Sacha Epskamp

It is quite weird and I have no clue at moment either. There is no need to comment out lines 82-85. It seems that when you call "opt.minimize(rb, x);" on line 106 and somehow this error has been triggered. Could you please check g++ version you're using on Windows (or the Rtools version)? And also could you please attach the figure of compile information on terminal(as we may find additional information over there).

Thanks!

**Comment by SachaEpskamp** [comment]
Hi Yi Pan,

Thank you for your quick reply! I installed Rtools35 which should be the latest, and apparently have G++ 4.9.3 (that seems low, I have a much higher version on Linux). See below for a screenshot:

![2020-03-26_13-48-00](https://user-images.githubusercontent.com/1207242/77648561-a2648500-6f68-11ea-89dc-dc48bdae5f1a.png)

Best, Sacha

**Comment by ypan1988** [comment]
Dear Sacha Epskamp

I have tried to compile your package on linux and it is okay. Actually it is quite hard for me to reproduce the error currently -- I left my only windows PC in the office, and obviously I cannot go back now. Could you please simply try the following change on your PC (as I get the feeling that "control" is somehow not regarded as data member in your case):

roptim.h:
Change 
> line 86:    } control; 

to
> };
> RoptimControl control;

I write the following simple code which might be helpful to find a solution to the problem:
test.cpp:
```c
#include <Rcpp.h>

template <typename T>
class A {
  T val = 10;
public:
  struct Inner{
    int trace = 0;
  };
  Inner control;
  void fun(T v) {
    val = v;
    if (control.trace > 0)
      Rcpp::Rcout << "val = " << val << std::endl;
  }
};

// [[Rcpp::export]]
void test_A()
{
  A<int> a;
  a.control.trace = 1;
  a.fun(20);
}
```

And run the following in R:
> library(Rcpp)
> sourceCpp("~/test.cpp")   # You may need to change the directory
> test_A()

If you are able to get the function test_A() above working, then it also means that we have fixed the problem.  

Thanks!

**Comment by ypan1988** [comment]
By the way, the version of Rtools you're using is definitely okay. And that's something I don't understand -- I was using the same Rtools and roptim in my package on Windows while there was no error.

**Comment by SachaEpskamp** [comment]
Thanks! The `test_A()` function works regardless of changing that line in roptim.h, but changing the line did not fix the problem in building the package.

**Comment by ypan1988** [comment]
Hi, Sacha

I managed to reproduce the error on windows vm and found that the following change may fix the problem:
roptim.h:
Change
> int trace = 0;

to
> std::size_t trace = 0;

Change
```c
if (control.trace < 0)
    Rcpp::warning("read the documentation for 'trace' more carefully");
else if (method_ == "SANN" && control.trace && control.REPORT == 0)
    Rcpp::stop("'trace != 0' needs 'REPORT >= 1'");
```
to
```c
if (method_ == "SANN" && control.trace && control.REPORT == 0)
    Rcpp::stop("'trace != 0' needs 'REPORT >= 1'");
```

Let me know if it also works for you. Thanks a lot!

**Comment by SachaEpskamp** [comment]
Yes this worked! Thank you so much for the quick work on this!

**Comment by ypan1988** [comment]
It seems that it is a bug of the compiler. But I am still quite confused about this error -- I was doing something similar in my another package and I should get this error message long time ago. 

Anyway I will aim to update the package this weekend and afterwards you can specify the minimum roptim version required in the DESCRIPTION file for safe. Thanks.

**Comment by SachaEpskamp** [comment]
That is great, thank! Of note, I obtained a similar error on a Linux high performance cloud that was also fixed with this code.
